### ISSUE TITLE
'psutil' has no attribute 'MACOS' - Python 3.6.4 on Mac OS 10.14.1

### ISSUE THREAD

**Issue by aditisrinivas97** [giampaolo/psutil#1391]
As psutil for python 3.6.4 does not have an attribute named MACOS, the script `scripts/procsmem.py` fails.

Works fine in Python 2.7 as it has the attribute.

**Comment by giampaolo** [comment]
Can't reproduce as of psutil version 5.5.1. I'm quite positive on thinking you're using an older psutil version with a newer script somehow.
