### ISSUE TITLE
AttributeError: 'Process' object has no attribute 'rlimit'

### ISSUE THREAD

**Issue by aleoliva** [giampaolo/psutil#831]
Hi Giampaolo,

First, thanks for psutil library. It's just great!

but I cannot get rlimit() working with psutil v4.2.0:
```bash
$ python
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil 
>>> p = psutil.Process()
>>> p.cmdline()
['python']
>>> p.rlimit(psutil.RLIMIT_NOFILE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Process' object has no attribute 'rlimit'
```

My environment:
```bash
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)
$ python -V
Python 2.6.6
```

Thanks in advance for your support,

Alejandro

**Comment by giampaolo** [comment]
prlimit availability is determined at runtime here:
https://github.com/giampaolo/psutil/blob/master/psutil/_psutil_linux.c#L45
Are you satisfying those conditions (Linux >= 2.6.36, glibc >= 13)?

**Comment by aleoliva** [comment]
I see, so my system is too old:
glibc-2.12-1.149.el6_6.7.i686
Linux <hostname> 2.6.32-504.16.2.el6.x86_64 [...]

Is a requirement for prlimit these minimum versions of kernel and glibc? Or just, it was never tested on older systems?

I am asking so because I am thinking about the possibility to compile the library skipping these controls, and I would like to have your feedback.

Regards

**Comment by aleoliva** [comment]
I answer myself:
It is required for solving issue [#438](https://code.google.com/archive/p/psutil/issues/438).

So I will try to survive without rlimit()

Thanks all in all.

**Comment by giampaolo** [comment]
Yes, it's just too old. On the bright side, if you need to set limits **for your own process** you can use stdlib resource module (https://docs.python.org/2/library/resource.html) which It does exactly the same thing.

**Comment by aleoliva** [comment]
Yes, but my goal is some kind of monitor for all running processes, so I need a getrlimit() for all processes, not only the current process or its children.

**Comment by giampaolo** [comment]
I see. Well then the only option is to upgrade your distro. :)
Il 09/giu/2016 11:43, "aleoliva" <notifications@github.com> ha scritto:

**Comment by aleoliva** [comment]
It looks so. 8)

Thanks for your support,

Alejandro
