### ISSUE TITLE
'psutil' has no attribute 'sensors_temperatures'

### ISSUE THREAD

**Issue by App24** [giampaolo/psutil#1271]
I just tried to use psutil, but psutil.sensors_temperatures() currently returns an error
`Traceback (most recent call last):
  File "C:/Users/Owner/Desktop/test.py", line 2, in <module>
    print(psutil.sensors_temperatures())
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'`
Using Windows 10

**Comment by ZORfree** [comment]
me too！！！ Have you solved the problem？

**Comment by giampaolo** [comment]
If you read the doc you'll notice how that is Linux only for now. =)

**Comment by Changlei123** [comment]
I have the same story! Python 3.7

**Comment by alex37529** [comment]
i have same issue at Ubuntu
```
>>> psutil.sensors_temperatures()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'
```

**Comment by amanusk** [comment]
@alex37529, what version of `pstutil` do you have?
I believe it was added in 5.1.0
You can check with `python -c "import psutil; print(psutil.__version__)"`

**Comment by KarinWillers** [comment]
I have version 5.5.0 and it is not working for me with Python 2.7.15 under Windows 7.
The psutil documentation says:

Availability: Linux, FreeBSD
New in version 5.1.0.
Changed in version 5.5.0: added FreeBSD support

**Comment by giampaolo** [comment]
sensors_temperatures() is currently not implemented on windows

**Comment by lamoboos223** [comment]
i'm on mac and have version 5.6.3 and have the same problem

**Comment by amanusk** [comment]
@lamoboos223, as per [documentation](https://psutil.readthedocs.io/en/latest/#psutil.sensors_temperatures), temperatures sensors are currently only available on Linux and FreeBSD platforms.

**Comment by jnrmenariya** [comment]
psutil.sensors_temperatures(fahrenheit=False) is currently available only for :: Linux, FreeBSD

Also psutil.sensors_fans() is available only for  Linux, macOS.

the only thing u can do is put them in try catch so that you can continue further without termination of execution of code. 

	# Getting Temp info
	try:
		GenLogs("Hardware Temperatur :",psutil.sensors_temperatures(fahrenheit=False))
		
	except Exception as e:
		GenLogs("Exeption has occured :",str(e))

	# Getting fan speed
	try:
		GenLogs("Fan Speed :",psutil.sensors_fans())
	except Exception as e:
		GenLogs("Exeption has occured :",str(e))

**Comment by matteos1** [comment]
how is it possible to update the version of psutil on linux?

**Comment by robinechuca** [comment]
> how is it possible to update the version of psutil on linux?

in a terminal you can hit: "python3 -m pip install --upgrade psutil"

**Comment by mkanet** [comment]
I'm not sure if anyone's still following this issue.. but, is there any plans to gain temperature information for Windows in psutil?

**Comment by giampaolo** [comment]
I can't do it because I have a virtualized Windows box (would need a real one). Last time I checked it seems this can be done via the WMI interface. So basically whoever wants to give it a try just make a PR for it.

**Comment by mkanet** [comment]
Thanks for the respons of @giampaolo.  In my case, I was trying to expose this information ultimately in the Glances API; which depends on Psutil.

**Comment by alvinbengeorge** [comment]
@giampaolo, I think I have a solution to this, you can use WMI for this right? If we can use that, we might get the temperature in Windows 10. I checked the internet, and I found out that we need a dll file from an application called OpenHardwareMonitor
Thank You

**Comment by giampaolo** [comment]
We can't use external DLLs. My comment about WMI meant that the implementation should be done by using WMI interface in C.

**Comment by alvinbengeorge** [comment]
Oh ok, thank you for the information, Big fan of your work

**Comment by giampaolo** [comment]
Thank you, I appreciate it.

**Comment by mkanet** [comment]
Is there a way to have a multi-platform solution for temperatures?  Even if there's a solution for Windows, it still wouldn't work for Mac users.

**Comment by MD-khan** [comment]
Same story here

**Comment by hulitolku** [comment]
When fix this trouble?

**Comment by mkanet** [comment]
I would be very happy with a solution on Windows.

**Comment by jjziets** [comment]
im not getting psutil.sensors_temperatures(fahrenheit=False) to work on lunix ubunut 20.04 

>>> import psutil
>>> psutil.sensors_temperatures(fahrenheit=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'sensors_temperatures'

**Comment by jasmeralia** [comment]
This should be reopened as a feature request, not closed as completed; that's very misleading. Even if you aren't going to be the one to implement it, someone else who does should still be associating it with an open issue, and having an open feature request will make it easier for people to understand why it's not working. Also, the PyPi page should be updated to indicate that the sensor functions are only supported on Linux and FreeBSD. There's no mention there of this limitation, while it does say that Windows is a supported platform, which again is misleading. 

I'm not super familiar with WMI, but I'll do some digging and see if I can come up with something for the Windows side. 

I do have a MacBook as well, and I'd previously done some stuff with temperatures in htop-osx. I'll see if I can dig that out and see if it provides any guidance. That was C rather than Python, but I know there are ways to leverage C code in Python if necessary. That said, I have an older Intel-based MacBook (which they don't make anymore), so I can't really speak to Apple Silicon.

It's possible I could get it to work on a `mac2.metal` EC2 instance, since those are actually Apple Silicon Mac Minis run in AWS, but there's a minimum 24h billing charge for those, and I'm not entirely sure if there's a virtualization layer on top of the hardware... I know it's a 1:1 allocation between the EC2 instance ahd the Mac Mini dedicated host, so I suspect it's probably just some provisioning tweaks over the bare metal, but I'm not 100% confident of that.
