### PR TITLE
Fix #1528: [AIX] use correct definition of size of procbuf

### LINKED ISSUE #1528: AIX 7.2 Failed to build psutil - "incomplete type 'struct procinfo'" when running gcc
**Platform**
* OS: AIX 7.2
* Python version: 3.6.6
* psutil version: 5.6.3
* gcc version: 7.2.0
* wheel version (installed in venv): 0.29.0

**Bug description**
Newest release of Psutil - **5.6.3** - doesn't compile on AIX 7.2.
Version **5.6.2** was building properly.

```
psutil/_psutil_aix.c: In function 'psutil_proc_args':
psutil/_psutil_aix.c:183:36: error: invalid application of 'sizeof' to incomplete type 'struct procinfo'
     ret = getargs(&procbuf, sizeof(struct procinfo), argbuf, ARG_MAX);
                                    ^~~~~~
psutil/_psutil_aix.c: In function 'psutil_proc_environ':
psutil/_psutil_aix.c:244:37: error: invalid application of 'sizeof' to incomplete type 'struct procinfo'
     ret = getevars(&procbuf, sizeof(struct procinfo), envbuf, ARG_MAX);
                                     ^~~~~~
error: command 'gcc' failed with exit status 1
```

**Way to reproduce**
```/path/to/python_venv/bin/python3 /path/to/psutil-5.6.3/setup.py clean --all bdist_wheel -b /path/to/psutil-5.6.3_tmp -d /path/to/psutil-5.6.3_wheel```

### PR DESCRIPTION
**Pull request by wiggin15**

### CODE REVIEW

**Comment by giampaolo** [comment]
Sorry, I merged too soon.

**Comment by wiggin15** [comment]
@pawelmy are you sure you are using the file from the latest version? The lines that failed for you were changed to have `sizeof(procbuf)`, but somehow you have `sizeof(procinfo)` which looks like an incorrect manual modification.

**Comment by pawelmy** [comment]
Oh damn, my bad... Works fine. Sorry for the confusion.
