### ISSUE TITLE
AIX 7.2 Failed to build psutil - "incomplete type 'struct procinfo'" when running gcc

### ISSUE THREAD

**Issue by pawelmy** [giampaolo/psutil#1528]
**Platform**
* OS: AIX 7.2
* Python version: 3.6.6
* psutil version: 5.6.3
* gcc version: 7.2.0
* wheel version (installed in venv): 0.29.0

**Bug description**
Newest release of Psutil - **5.6.3** - doesn't compile on AIX 7.2.
Version **5.6.2** was building properly.

```
psutil/_psutil_aix.c: In function 'psutil_proc_args':
psutil/_psutil_aix.c:183:36: error: invalid application of 'sizeof' to incomplete type 'struct procinfo'
     ret = getargs(&procbuf, sizeof(struct procinfo), argbuf, ARG_MAX);
                                    ^~~~~~
psutil/_psutil_aix.c: In function 'psutil_proc_environ':
psutil/_psutil_aix.c:244:37: error: invalid application of 'sizeof' to incomplete type 'struct procinfo'
     ret = getevars(&procbuf, sizeof(struct procinfo), envbuf, ARG_MAX);
                                     ^~~~~~
error: command 'gcc' failed with exit status 1
```

**Way to reproduce**
```/path/to/python_venv/bin/python3 /path/to/psutil-5.6.3/setup.py clean --all bdist_wheel -b /path/to/psutil-5.6.3_tmp -d /path/to/psutil-5.6.3_wheel```

**Comment by giampaolo** [comment]
CC @wiggin15

**Comment by wiggin15** [comment]
@pawelmy can you please try to add a line `#include <procinfo.h>` to `psutil/_psutil_aix.c` and see if it then compiles successfully?

**Comment by pawelmy** [comment]
@wiggin15 Just tried multiple runs, with insertion in different lines each time. The same issue occurs consistently.

**Comment by wiggin15** [comment]
That's strange. I can't reproduce this behavior. The only thing that may be relevant that changed from 5.6.2 to 5.6.3 in AIX is the order of the include files, but I don't think it matters.
Can you please try to compile a test file?
```C
#include <procinfo.h>
void main(void)
{
	struct procinfo test;
}
```
Put it in `test.c` and run `gcc test.c`. Please let us know if it compiles successfully.

**Comment by gmc444-b** [comment]
I'm using the native xlc_r compiler and get a slightly different error, but it looks like it's the same root cause:
```
xlc_r -q64 -qarch=pwr6 -qtune=pwr7 -qdfp -qmaxmem=-1 -DNDEBUG -O -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=563 -DPSUTIL_AIX=1 -c psutil/_psutil_aix.c -o build/temp.aix-7.1-2.7/psutil/_psutil_aix.o

    "psutil/_psutil_aix.c", line 183.29: 1506-043 (S) The operand of the sizeof operator is not valid.
```

Examining the `/usr/include/procinfo.h` file, it looks like `procinfo` is only defined for 32-bit architectures, and for 64-bit, it's named `procsinfo`.

**Comment by wiggin15** [comment]
Thanks @gmc444-b . This helps.
The note in `procinfo.h` says:
```
/*
 * Warning: the procinfo, userinfo, and uicredinfo structures represent
 * obsolete interfaces.  These would not compile correctly in 64-bit mode.
 */
```
Compiling my test program with `-maix64` reproduces the problem.

We should use `procsinfo` instead (for both modes), which is how the buffers we are passing are defined in the first place... (we have `struct procsinfo procbuf` but we pass its size with `sizeof(struct procinfo)`...).

I was wrong before about what changed between 5.6.2 and 5.6.3. We added the code that uses `getargs` and `getevars` with this broken definition.

**Comment by pawelmy** [comment]
Just to confirm - changing all entries of `procinfo` to `procsinfo` in `psutil/_psutil_aix.c` fixed the issue.
Great catch @gmc444-b

**Comment by wiggin15** [comment]
Opened PR #1533.
