### ISSUE TITLE
psutil won't compile on OSX 10.4

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#790]
Error:

```
psutil/_psutil_osx.c: In function 'psutil_proc_memory_uss':
psutil/_psutil_osx.c:625: error: 'SM_LARGE_PAGE' undeclared (first use in this function)
psutil/_psutil_osx.c:625: error: (Each undeclared identifier is reported only once
psutil/_psutil_osx.c:625: error: for each function it appears in.)
```
