### ISSUE TITLE
[Any] 'Error' object has no attribute 'msg'

### ISSUE THREAD

**Issue by fstagni** [giampaolo/psutil#2048]
## Summary

* OS: { ANY }
* Architecture: { ANY }
* Psutil version: { 5.9.0 }
* Python version: { 3.9.7 (any, really) }
* Type: { core }

## Description

I believe this is a bug:

```python
>>> try:
...     raise psutil.Error
... except psutil.Error as err:
...     print(err)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
psutil.Error: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/fstagni/mambaforge/envs/dirac-development/lib/python3.9/site-packages/psutil/_common.py", line 300, in __str__
    return " ".join([x for x in (self.msg, details) if x])
AttributeError: 'Error' object has no attribute 'msg'
```
Version 5.8.0 was printing correctly. Caused by https://github.com/giampaolo/psutil/commit/5d39cc9c8d8dc04862786abba0307ed9350144ce
